export const BTN_CHANGE = 'BTN_CHANGE';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_DEVICES = 'CHANGE_DEVICES';
export const CHANGE_LOCATIONS = 'CHANGE_LOCATIONS';
export const CHECK_POWER = 'CHECK_POWER';
